### ISSUE TITLE
JasminIntegrationSample erro de ligação

### ISSUE THREAD

**Issue by hmapedro** [jasminsoftware/Resources#13]
Estou a tentar utilizar o Exemplo de Integração ao Software Jasmin disponível no GitHub e quando me tento ligar a uma subscrição que tenho dá o seguinte erro:
As documents are company dependent entities, for this sample, we will need to
get the company key where we will be acting upon
Request – GET
https://my.jasminsoftware.com/api/248181/248181-0001/corepatterns/companies/odata?$select=CompanyKey&$filter=IsActive eq true and IsSystem eq false and IsDeleted eq false &$top=1&$orderby=CreatedOn
Error found!
Specified cast is not valid.
One or more errors occurred. (Error geting the current company.)
 
Alguém tem alguma ideia do que se pode estar a passar?
 
Obrigado.

**Comment by EduardoJSilva** [comment]
Bom dia.
Revalidamos o código disponibilizado em  várias das nossas subscrições e não conseguimos reproduzir o problema. 
Pelo que percebemos :
1. Já tem o seu clientid e client secret 
2. Consegue efetuar o pedido do token
3. Este erro ocorre no momento do pedido odata no qual ocorre um erro não tratado.

Analisando a questão do lado da infraestrutura poderá ter ocorrido um problema aparentemente relacionado com cache do servidor, após ter efetuado o primeiro pedido falhado que o impediu de prosseguir. 

Julgamos que tal probelma está já solucionado e não se tratando de um bug do código ou dúvida sobre a implementação iremos fechar este issue.

Caso o problema continue a ocorrer sugiro que contacte o suporte do Jasmim, através do chat.
